import { getCurrentUserAccess } from "@/lib/auth/current-user";
import { getUserNotifications } from "@/features/enquiries/service";
import { hasDatabaseConfiguration } from "@/lib/env";
import { formatDate } from "@/lib/utils";

export default async function AdminNotificationsPage() {
  const access = await getCurrentUserAccess();
  const result = access.mode === "authorized" && hasDatabaseConfiguration() ? await getUserNotifications(access.profile.id) : { connected: false as const, notifications: [] };
  return <section className="space-y-8"><header><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Updates</p><h1 className="mt-2 font-serif text-4xl">Notifications</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Status changes and review updates scoped to your authenticated workspace profile.</p></header>{!result.connected ? <div className="rounded-2xl border border-dashed border-border p-8"><h2 className="font-serif text-3xl">Notifications are waiting for database setup.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">No user-specific records are shown until the workspace database is available.</p></div> : result.notifications.length === 0 ? <div className="rounded-2xl border border-dashed border-border p-8"><h2 className="font-serif text-3xl">You are up to date.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">New moderation and enquiry updates will appear here.</p></div> : <div className="grid gap-3">{result.notifications.map((notification) => <article className={`rounded-2xl border p-5 ${notification.readAt ? "border-border bg-card" : "border-primary/30 bg-primary/5"}`} key={notification.id}><div className="flex items-start justify-between gap-4"><div><h2 className="font-bold">{notification.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{notification.body}</p></div><time className="shrink-0 text-xs text-muted-foreground" dateTime={notification.createdAt.toISOString()}>{formatDate(notification.createdAt)}</time></div>{!notification.readAt && <form action={`/api/admin/notifications/${notification.id}`} className="mt-4" method="post"><button className="text-xs font-bold text-primary" type="submit">Mark as read</button></form>}</article>)}</div>}</section>;
}
