import Link from "next/link";

import { EnquiryAssignment } from "@/components/admin/enquiry-assignment";
import { EnquiryStatusActions } from "@/components/admin/enquiry-status-actions";
import { getActiveStaff, getAdminEnquiries } from "@/features/enquiries/service";
import { hasDatabaseConfiguration } from "@/lib/env";
import { formatDate } from "@/lib/utils";

export default async function AdminEnquiriesPage() {
  const result = hasDatabaseConfiguration() ? await getAdminEnquiries() : { connected: false as const, enquiries: [] };
  const staffResult = result.connected ? await getActiveStaff() : { connected: false as const, staff: [] };
  return <section className="space-y-8"><header><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Conversations</p><h1 className="mt-2 font-serif text-4xl">Enquiries</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Move incoming questions through a visible pipeline. A site-visit request is not a booking.</p></header>{!result.connected ? <div className="rounded-2xl border border-dashed border-border p-8"><h2 className="font-serif text-3xl">Connect the workspace database.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Public enquiry intake is ready, but the operational queue needs the Supabase database connection.</p><Link className="mt-6 inline-flex min-h-11 items-center rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground" href="/admin/settings">Open setup notes</Link></div> : result.enquiries.length === 0 ? <div className="rounded-2xl border border-dashed border-border p-8"><h2 className="font-serif text-3xl">No active enquiries.</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">New public messages will appear here with their source and current status.</p></div> : <div className="grid gap-4">{result.enquiries.map((enquiry) => <article className="rounded-2xl border border-border bg-card p-5 sm:p-6" key={enquiry.id}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-muted px-2.5 py-1 text-[11px] font-bold uppercase tracking-wide text-primary">{enquiry.status.toLowerCase().replaceAll("_", " ")}</span><span className="text-xs text-muted-foreground">{enquiry.type.toLowerCase().replaceAll("_", " ")}</span></div><h2 className="mt-4 text-lg font-bold">{enquiry.contactName}</h2><p className="mt-1 text-sm text-muted-foreground">{enquiry.email}{enquiry.phone ? ` · ${enquiry.phone}` : ""}</p></div><time className="text-xs text-muted-foreground" dateTime={enquiry.createdAt.toISOString()}>{formatDate(enquiry.createdAt)}</time></div><p className="mt-5 whitespace-pre-line text-sm leading-7 text-muted-foreground">{enquiry.message}</p>{enquiry.property && <p className="mt-4 text-xs font-semibold text-primary">{enquiry.property.referenceNumber} · {enquiry.property.title}</p>}<p className="mt-4 text-xs text-muted-foreground">Assigned: {enquiry.assignedAdmin?.displayName || enquiry.assignedAdmin?.email || "Unassigned"}</p><EnquiryAssignment id={enquiry.id} assignedAdminId={enquiry.assignedAdminId} staff={staffResult.staff} /><EnquiryStatusActions id={enquiry.id} status={enquiry.status} /></article>)}</div>}</section>;
}
